import { NextRequest, NextResponse } from "next/server";
import { readFile, writeFile } from "fs/promises";
import { join } from "path";
import { Article } from "@/types/article";

const DATA_FILE = join(process.cwd(), "data", "articles.ts");

// Generate articles file content (same pattern as other routes)
function generateArticlesFile(articles: Article[]): string {
  const indent = "  ";
  let content = `import { Article } from "@/types/article";\n\n`;
  content += `// Articles data - add your articles here\n`;
  content += `// This file is auto-generated by admin panel. Manual edits may be overwritten.\n`;
  content += `export const articles: Article[] = [\n`;

  articles.forEach((article, index) => {
    content += `${indent}{\n`;
    content += `${indent}${indent}id: ${JSON.stringify(article.id)},\n`;
    content += `${indent}${indent}title: ${JSON.stringify(article.title)},\n`;
    content += `${indent}${indent}slug: ${JSON.stringify(article.slug)},\n`;
    content += `${indent}${indent}category: ${JSON.stringify(article.category)},\n`;
    content += `${indent}${indent}content: ${JSON.stringify(article.content)},\n`;
    if (article.excerpt) {
      content += `${indent}${indent}excerpt: ${JSON.stringify(article.excerpt)},\n`;
    }
    if (article.featuredImage) {
      content += `${indent}${indent}featuredImage: ${JSON.stringify(article.featuredImage)},\n`;
    }
    content += `${indent}${indent}tags: ${JSON.stringify(article.tags)},\n`;
    content += `${indent}${indent}author: ${JSON.stringify(article.author)},\n`;
    content += `${indent}${indent}published: ${article.published},\n`;
    if (article.publishedAt) {
      content += `${indent}${indent}publishedAt: ${JSON.stringify(article.publishedAt)},\n`;
    }
    content += `${indent}${indent}createdAt: ${JSON.stringify(article.createdAt)},\n`;
    content += `${indent}${indent}updatedAt: ${JSON.stringify(article.updatedAt)},\n`;
    if (article.seoTitle) {
      content += `${indent}${indent}seoTitle: ${JSON.stringify(article.seoTitle)},\n`;
    }
    if (article.seoDescription) {
      content += `${indent}${indent}seoDescription: ${JSON.stringify(article.seoDescription)},\n`;
    }
    if (article.seoKeywords) {
      content += `${indent}${indent}seoKeywords: ${JSON.stringify(article.seoKeywords)},\n`;
    }
    content += `${indent}${indent}allowComments: ${article.allowComments},\n`;
    if (article.commentCount !== undefined) {
      content += `${indent}${indent}commentCount: ${article.commentCount},\n`;
    }
    if (article.views !== undefined) {
      content += `${indent}${indent}views: ${article.views},\n`;
    }
    content += `${indent}}${index < articles.length - 1 ? "," : ""}\n`;
  });

  content += `];\n`;
  return content;
}

// POST - Increment article view count
export async function POST(request: NextRequest) {
  try {
    const { articleId } = await request.json();

    if (!articleId) {
      return NextResponse.json({ error: "articleId required" }, { status: 400 });
    }

    const { articles: allArticles } = await import("@/data/articles");
    const articleIndex = allArticles.findIndex(a => a.id === articleId);

    if (articleIndex === -1) {
      return NextResponse.json({ error: "Article not found" }, { status: 404 });
    }

    // Increment views
    const currentViews = allArticles[articleIndex].views || 0;
    allArticles[articleIndex] = {
      ...allArticles[articleIndex],
      views: currentViews + 1,
    };

    const newContent = generateArticlesFile(allArticles);
    await writeFile(DATA_FILE, newContent, "utf-8");

    return NextResponse.json({
      success: true,
      views: allArticles[articleIndex].views,
    });
  } catch (error) {
    console.error("Error incrementing article views:", error);
    return NextResponse.json(
      { error: "Failed to update view count" },
      { status: 500 }
    );
  }
}
