import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { writeFile } from "fs/promises";
import { join } from "path";
import { Article } from "@/types/article";
import { getArticles, saveArticlesToBlob } from "@/lib/articlesData";

const DATA_FILE = join(process.cwd(), "data", "articles.ts");

// Check authentication
async function checkAuth() {
  const cookieStore = await cookies();
  return cookieStore.get("admin-auth")?.value === "true";
}

// Generate articles file content
function generateArticlesFile(articles: Article[]): string {
  const indent = "  ";
  let content = `import { Article } from "@/types/article";\n\n`;
  content += `// Articles data - add your articles here\n`;
  content += `// This file is auto-generated by admin panel. Manual edits may be overwritten.\n`;
  content += `export const articles: Article[] = [\n`;

  articles.forEach((article, index) => {
    content += `${indent}{\n`;
    content += `${indent}${indent}id: ${JSON.stringify(article.id)},\n`;
    content += `${indent}${indent}title: ${JSON.stringify(article.title)},\n`;
    content += `${indent}${indent}slug: ${JSON.stringify(article.slug)},\n`;
    content += `${indent}${indent}category: ${JSON.stringify(article.category)},\n`;
    content += `${indent}${indent}content: ${JSON.stringify(article.content)},\n`;
    if (article.excerpt) {
      content += `${indent}${indent}excerpt: ${JSON.stringify(article.excerpt)},\n`;
    }
    if (article.featuredImage) {
      content += `${indent}${indent}featuredImage: ${JSON.stringify(article.featuredImage)},\n`;
    }
    if (article.images && article.images.length > 0) {
      content += `${indent}${indent}images: [${article.images.map(img => JSON.stringify(img)).join(", ")}],\n`;
    }
    content += `${indent}${indent}tags: [${article.tags.map(tag => JSON.stringify(tag)).join(", ")}],\n`;
    content += `${indent}${indent}author: ${JSON.stringify(article.author)},\n`;
    content += `${indent}${indent}published: ${article.published},\n`;
    if (article.publishedAt) {
      content += `${indent}${indent}publishedAt: ${JSON.stringify(article.publishedAt)},\n`;
    }
    content += `${indent}${indent}createdAt: ${JSON.stringify(article.createdAt)},\n`;
    content += `${indent}${indent}updatedAt: ${JSON.stringify(article.updatedAt)},\n`;
    if (article.seoTitle) {
      content += `${indent}${indent}seoTitle: ${JSON.stringify(article.seoTitle)},\n`;
    }
    if (article.seoDescription) {
      content += `${indent}${indent}seoDescription: ${JSON.stringify(article.seoDescription)},\n`;
    }
    if (article.seoKeywords && article.seoKeywords.length > 0) {
      content += `${indent}${indent}seoKeywords: [${article.seoKeywords.map(kw => JSON.stringify(kw)).join(", ")}],\n`;
    }
    content += `${indent}${indent}allowComments: ${article.allowComments},\n`;
    if (article.commentCount !== undefined) {
      content += `${indent}${indent}commentCount: ${article.commentCount},\n`;
    }
    if (article.views !== undefined) {
      content += `${indent}${indent}views: ${article.views},\n`;
    }
    content += `${indent}}${index < articles.length - 1 ? "," : ""}\n`;
  });

  content += `];\n`;
  return content;
}

// GET - Get all articles (public can see published, admin sees all)
export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const category = searchParams.get("category");
    const published = searchParams.get("published");

    const importedArticles = await getArticles();
    let filtered = [...importedArticles];
    
    // Filter by category
    if (category) {
      filtered = filtered.filter(a => a.category === category);
    }
    
    // Filter by published status (public sees only published)
    const isAdmin = await checkAuth();
    if (published === "true" || !isAdmin) {
      filtered = filtered.filter(a => a.published);
    }
    
    return NextResponse.json({ articles: filtered });
  } catch (error) {
    console.error("Error reading articles:", error);
    return NextResponse.json({ articles: [] });
  }
}

// POST - Create new article
export async function POST(request: Request) {
  if (!(await checkAuth())) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const articleData: any = await request.json();
    const existingArticles = await getArticles();
    
    // Generate slug from title if not provided
    const slug = articleData.slug || articleData.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');
    
    // Check if slug already exists
    if (existingArticles.some(a => a.slug === slug && a.category === articleData.category)) {
      return NextResponse.json(
        { error: "Article with this slug already exists in this category" },
        { status: 400 }
      );
    }
    
    const newArticle: Article = {
      id: articleData.id || `article-${Date.now()}`,
      title: articleData.title,
      slug,
      category: articleData.category,
      content: articleData.content || "",
      excerpt: articleData.excerpt,
      featuredImage: articleData.featuredImage,
      images: articleData.images || [],
      tags: articleData.tags || [],
      author: articleData.author || "Admin",
      published: articleData.published || false,
      publishedAt: articleData.published ? new Date().toISOString() : undefined,
      createdAt: articleData.createdAt || new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      seoTitle: articleData.seoTitle,
      seoDescription: articleData.seoDescription,
      seoKeywords: articleData.seoKeywords || [],
      allowComments: articleData.allowComments !== false,
      commentCount: 0,
    };
    
    const updatedArticles = [...existingArticles, newArticle];
    if (process.env.BLOB_READ_WRITE_TOKEN) {
      await saveArticlesToBlob(updatedArticles);
    } else {
      const newContent = generateArticlesFile(updatedArticles);
      await writeFile(DATA_FILE, newContent, "utf-8");
    }
    return NextResponse.json({ article: newArticle });
  } catch (error) {
    console.error("Error creating article:", error);
    return NextResponse.json(
      { error: "Failed to create article" },
      { status: 500 }
    );
  }
}

// PUT - Update article
export async function PUT(request: Request) {
  if (!(await checkAuth())) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const articleData: any = await request.json();
    const existingArticles = await getArticles();

    const index = existingArticles.findIndex((a) => a.id === articleData.id);
    if (index === -1) {
      return NextResponse.json({ error: "Article not found" }, { status: 404 });
    }

    const updatedArticle: Article = {
      ...existingArticles[index],
      ...articleData,
      updatedAt: new Date().toISOString(),
    };

    existingArticles[index] = updatedArticle;
    if (process.env.BLOB_READ_WRITE_TOKEN) {
      await saveArticlesToBlob(existingArticles);
    } else {
      const newContent = generateArticlesFile(existingArticles);
      await writeFile(DATA_FILE, newContent, "utf-8");
    }
    return NextResponse.json({ article: updatedArticle });
  } catch (error) {
    console.error("Error updating article:", error);
    return NextResponse.json(
      { error: "Failed to update article" },
      { status: 500 }
    );
  }
}

// DELETE - Delete article
export async function DELETE(request: Request) {
  if (!(await checkAuth())) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get("id");

    if (!id) {
      return NextResponse.json({ error: "ID required" }, { status: 400 });
    }

    const existingArticles = await getArticles();
    const filtered = existingArticles.filter((a) => a.id !== id);

    if (process.env.BLOB_READ_WRITE_TOKEN) {
      await saveArticlesToBlob(filtered);
    } else {
      const newContent = generateArticlesFile(filtered);
      await writeFile(DATA_FILE, newContent, "utf-8");
    }
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Error deleting article:", error);
    return NextResponse.json(
      { error: "Failed to delete article" },
      { status: 500 }
    );
  }
}
