import { Property } from "@/types/property";
import { normalizePropertyFeatures, PROPERTY_FEATURE_KEYS } from "@/lib/featureState";

/** IDR/USD amounts are whole rupiah/cents in admin; avoid float tails in generated TS. */
function toIntegerPrice(n: unknown): number {
  if (typeof n === "number" && Number.isFinite(n)) return Math.round(n);
  if (typeof n === "string" && n.trim() !== "") {
    const v = Number(n);
    return Number.isFinite(v) ? Math.round(v) : 0;
  }
  return 0;
}

export function generatePropertiesFile(properties: Property[]): string {
  const indent = "  ";
  let content = `import { Property } from "@/types/property";\n\n`;
  content += `// Property data - add your villas here\n`;
  content += `// This file is auto-generated by admin panel or CSV import. Manual edits may be overwritten.\n`;
  content += `export const properties: Property[] = [\n`;

  properties.forEach((prop, index) => {
    content += `${indent}{\n`;
    content += `${indent}${indent}id: ${JSON.stringify(prop.id)},\n`;
    if (prop.title != null && prop.title !== "") {
      content += `${indent}${indent}title: ${JSON.stringify(prop.title)},\n`;
    }
    if (prop.villaNumber != null && prop.villaNumber !== "") {
      content += `${indent}${indent}villaNumber: ${JSON.stringify(prop.villaNumber)},\n`;
    }
    if (prop.internalName != null && prop.internalName !== "") {
      content += `${indent}${indent}internalName: ${JSON.stringify(prop.internalName)},\n`;
    }
    /** Emit types & location before description so parseProperties' first `types:` match is never inside description text. */
    content += `${indent}${indent}types: [${(prop.types || []).map((t) => JSON.stringify(t)).join(", ")}],\n`;
    content += `${indent}${indent}mainArea: ${JSON.stringify(prop.mainArea || "ubud")},\n`;
    if (prop.subArea != null) {
      content += `${indent}${indent}subArea: ${JSON.stringify(prop.subArea)},\n`;
    }
    content += `${indent}${indent}description: ${JSON.stringify(prop.description ?? "")},\n`;
    if (prop.exactLocation != null && prop.exactLocation !== "") {
      content += `${indent}${indent}exactLocation: ${JSON.stringify(prop.exactLocation)},\n`;
    }
    if (prop.displayLocation != null && prop.displayLocation !== "") {
      content += `${indent}${indent}displayLocation: ${JSON.stringify(prop.displayLocation)},\n`;
    }
    if (prop.youtubeVideoUrl != null && prop.youtubeVideoUrl !== "") {
      content += `${indent}${indent}youtubeVideoUrl: ${JSON.stringify(prop.youtubeVideoUrl)},\n`;
    }
    content += `${indent}${indent}bedrooms: ${prop.bedrooms || 1},\n`;
    if (prop.bathrooms) {
      content += `${indent}${indent}bathrooms: ${prop.bathrooms},\n`;
    }
    if (prop.floors != null && prop.floors > 0) {
      content += `${indent}${indent}floors: ${prop.floors},\n`;
    }
    content += `${indent}${indent}price: {\n`;
    content += `${indent}${indent}${indent}currency: ${JSON.stringify(prop.price?.currency || "IDR")},\n`;
    const minVal = toIntegerPrice(
      prop.price?.min ?? prop.price?.monthly ?? prop.price?.forSale ?? 0
    );
    content += `${indent}${indent}${indent}min: ${minVal},\n`;
    if (prop.price?.monthly != null) {
      content += `${indent}${indent}${indent}monthly: ${toIntegerPrice(prop.price.monthly)},\n`;
    }
    if (prop.price?.yearly != null) {
      content += `${indent}${indent}${indent}yearly: ${toIntegerPrice(prop.price.yearly)},\n`;
    }
    if (prop.price?.forSale != null) {
      content += `${indent}${indent}${indent}forSale: ${toIntegerPrice(prop.price.forSale)},\n`;
    }
    content += `${indent}${indent}},\n`;
    if (prop.duration) {
      content += `${indent}${indent}duration: {\n`;
      content += `${indent}${indent}${indent}min: ${prop.duration.min},\n`;
      if (prop.duration.max) {
        content += `${indent}${indent}${indent}max: ${prop.duration.max},\n`;
      }
      content += `${indent}${indent}},\n`;
    }
    const feat = normalizePropertyFeatures(prop.features as Partial<Record<string, unknown>> | undefined);
    content += `${indent}${indent}features: {\n`;
    PROPERTY_FEATURE_KEYS.forEach((key, i) => {
      const comma = i < PROPERTY_FEATURE_KEYS.length - 1 ? "," : "";
      content += `${indent}${indent}${indent}${key}: ${JSON.stringify(feat[key])}${comma}\n`;
    });
    content += `${indent}${indent}},\n`;
    content += `${indent}${indent}images: [${(prop.images || []).map(img => JSON.stringify(img)).join(", ")}],\n`;
    if (prop.order !== undefined) {
      content += `${indent}${indent}order: ${prop.order},\n`;
    }
    if (prop.archived) {
      content += `${indent}${indent}archived: true,\n`;
    }
    if (prop.availableFrom != null && prop.availableFrom !== "") {
      content += `${indent}${indent}availableFrom: ${JSON.stringify(prop.availableFrom)},\n`;
    }
    content += `${indent}${indent}createdAt: ${JSON.stringify(prop.createdAt || new Date().toISOString())},\n`;
    if (prop.updatedAt) {
      content += `${indent}${indent}updatedAt: ${JSON.stringify(prop.updatedAt)},\n`;
    }
    content += `${indent}}${index < properties.length - 1 ? "," : ""}\n`;
  });

  content += `];\n`;
  return content;
}
